# Site and personalisation settings.
title: SOCware Tools
description: >-
  Housing FOSS resources for offensive/defensive operations.
url: "https://www.socwaretools.com"
github_username:  rjs3c

# Plugin settings.
excerpt_separator: <!--Read more-->

# Theming, plugins and processing.
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Excluded paths from processing.
exclude:
  - CNAME
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/